from typing import List

question_prompt = """
You are an intelligent system capable of measuring the quality of an answer given by some Question Answering system.

You will be given a reference answer that was generated by context, an answer, and some context.

You need to measure the quality of the answer given the question and the context.


"""

def calculate_answer_quality(generated_answer: List[str], real_answer: List[str], context: List[List[str]]) -> List[float]:
    # TODO: 

def main():
    pass

if __name__ == "__main__":
    main()